version: "3.5"
services:
    frontend:
        network_mode: host
        build:
            context: .
        volumes:
            - ../frontend:/frontend
        command: http-server dist --port 3002
