version: "3.5"
services:
    backend:
        network_mode: host
        build:
            context: .
        volumes:
            - ../backend:/server
        command: gunicorn -w 4 -b 0.0.0.0:3001 app:app
