- name: Stop and remove container
  vars:
    container_names:
      - elasticsearch
    containers: "{{ item }}"
  include_tasks: roles/common/tasks/docker_stop_remove_tasks.yml
  loop: "{{ container_names | batch(1) | list }}"
  tags:
    - elasticsearch

- name: Spin up new container
  docker_compose:
    project_src: "temp/compose/elasticsearch"
    build: yes
    debug: yes
  become: true
  register: started_containers
  tags:
    - elasticsearch

- name: Wait for elasticsearch to start
  uri:
    url: "http://localhost:9200/_recovery"
    method: GET
    return_content: yes
  register: _result
  until: _result.content == '{}'
  retries: 30 # retry X times
  delay: 5 # pause for X sec b/w each call

- name: Create base indexes
  shell:
    cmd: "python3 import_data.py"
    chdir: "temp/minitask"
  tags:
    - elasticsearch_base_indexes

- name: Create KNN indexes
  shell:
    cmd: "python index.py"
    chdir: "temp/knn_indexeing"
  tags:
    - elasticsearch_knn_indexes
